name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push App Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-fullstack-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-fullstack-app:latest

    - name: Build & Push ML Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-ml:latest ./mod els
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-ml:latest

    - name: Debug Docker Login
        run: echo "Username: ${{ secrets.DOCKER_USERNAME }}"